
import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'sv' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  sv: {
    'routeGame': 'Vägvalsspel',
    'courseSetter': 'Banläggare',
    'profile': 'Profil',
    'points': 'poäng',
    'routeChoose': 'Välj rutt',
    'routeInstruction': 'Välj rätt riktning för den här rutten för att tjäna poäng',
    'leaderboard': 'Topplista',
    'comingSoon': 'Kommer snart',
    'comingSoonDescription': 'Nya spännande funktioner på gång!',
    'orienteers': 'orienterare',
    'orienteeringEnthusiast': 'Orienteringsentusiast',
    'rank': 'Rankning',
    'yourStatistics': 'Dina statistik',
    'avgResponseTime': 'Genomsnittlig svarstid',
    'totalAttempts': 'Totala försök',
    'accuracy': 'Precision',
    'correctChoices': 'Korrekta val',
    'incorrectChoices': 'Felaktiga val',
    'you': 'du',
    'profileUpdated': 'Profil uppdaterad',
    'profileUpdateSuccess': 'Din profil har uppdaterats framgångsrikt',
    'invalidName': 'Ogiltigt namn',
    'nameEmpty': 'Namnet kan inte vara tomt',
    'excellent': 'Utmärkt!',
    'good': 'Bra!',
    'correct': 'Korrekt!',
    'wrong': 'Fel!',
    // Course Setter translations
    'newEvent': 'Nytt evenemang',
    'myMaps': 'Mina kartor',
    'mapUploadedSuccessfully': 'Kartan har laddats upp',
    'success': 'Framgång',
    'eventDate': 'Datum',
    'previewMode': 'Förhandsgranskningsläge',
    'editMode': 'Redigeringsläge',
    'print': 'Skriv ut',
    'toggleLayers': 'Växla lager',
    'export': 'Exportera',
    'back': 'Tillbaka',
    'save': 'Spara',
    'pointerTool': 'Pekare',
    'moveMap': 'Flytta karta',
    'addControl': 'Lägg till kontroll',
    'addStart': 'Lägg till start',
    'addFinish': 'Lägg till mål',
    'zoomIn': 'Zooma in',
    'zoomOut': 'Zooma ut',
    'advancedTools': 'Avancerade verktyg',
    'crossingPoint': 'Korsningspunkt',
    'uncrossableBoundary': 'Oöverstiglig gräns',
    'outOfBounds': 'Förbjudet område',
    'waterStation': 'Vattenstation',
    'resetView': 'Återställ vy',
    'printSettings': 'Utskriftsinställningar',
    'configurePrintSettingsFor': 'Konfigurera utskriftsinställningar för',
    'paperSize': 'Pappersstorlek',
    'selectPaperSize': 'Välj pappersstorlek',
    'orientation': 'Orientering',
    'portrait': 'Stående',
    'landscape': 'Liggande',
    'mapScale': 'Kartskala',
    'copies': 'Kopior',
    'include': 'Inkludera',
    'controlDescriptions': 'Kontrollbeskrivningar',
    'courseDetails': 'Bandetaljer',
    'cancel': 'Avbryt',
    'printArea': 'Utskriftsområde',
    'showCourses': 'Visa banor',
    'showControlNumbers': 'Visa kontrollnummer',
    'errorMapNotFound': 'Fel: Karta hittades inte',
    'myPurplePenProjects': 'Mina Purple Pen-projekt',
    'newProject': 'Nytt projekt',
    'previousProjects': 'Tidigare projekt',
    'viewManageProjects': 'Visa och hantera projekt',
    // Auth translations
    'signIn': 'Logga in',
    'signOut': 'Logga ut',
    'register': 'Registrera',
    'email': 'E-postadress',
    'password': 'Lösenord',
    'name': 'Namn',
    'fullName': 'Fullständigt namn',
    'signingIn': 'Loggar in...',
    'registering': 'Registrerar...',
    'signInError': 'Inloggningsfel',
    'signUpError': 'Registreringsfel',
    'signOutError': 'Utloggningsfel',
    'verifyEmail': 'Verifiera din e-post',
    'verifyEmailDescription': 'Vi har skickat en verifieringslänk till din e-post. Klicka på länken för att aktivera ditt konto.',
    'welcomeTo': 'Välkommen till',
    'authDescription': 'Logga in på ditt konto eller skapa ett nytt konto för att spara dina framsteg och tävla i topplistan.',
    'authDisclaimer': 'Genom att fortsätta godkänner du våra användarvillkor och integritetspolicy.',
    'guest': 'Gäst',
    'or': 'eller',
    'projectManager': 'Projekthanterare',
    'noCategories': 'Inga kategorier',
    'allCategories': 'Alla kategorier',
    'selectedCategories': 'Valda kategorier',
    'training': 'Träning',
    'club': 'Klubb',
    'national': 'Nationell',
    'other': 'Övrigt',
    'projectCreated': 'Projekt skapat',
    'hasBeenCreated': 'har skapats',
    'projectShared': 'Projekt delat',
    'projectSharedWith': 'Projektet har delats med',
    'permissionUpdated': 'Behörighet uppdaterad',
    'sharingPermissionUpdated': 'Delningsbehörigheten har uppdaterats',
    'accessRemoved': 'Åtkomst borttagen',
    'userAccessRemoved': 'Användarens åtkomst har tagits bort',
    'share': 'Dela',
    'sharedWith': 'Delat med',
    'error': 'Fel',
    'emailRequired': 'E-post krävs',
    'invalidEmail': 'Ogiltig e-postadress',
    'shareProject': 'Dela projekt',
    'shareProjectDescription': 'Bjud in andra användare att samarbeta på detta projekt',
    'enterName': 'Ange namn',
    'permission': 'Behörighet',
    'selectPermission': 'Välj behörighet',
    'canView': 'Kan se',
    'canSuggest': 'Kan föreslå',
    'canEdit': 'Kan redigera',
    'projectsList': 'Projektlista',
    'calendar': 'Kalender',
    'noProjects': 'Inga projekt',
    'createYourFirstProject': 'Skapa ditt första projekt',
    'createProject': 'Skapa projekt',
    'projectCalendar': 'Projektkalender',
    'viewUpcomingDeadlines': 'Se kommande deadlines',
    'noDescription': 'Ingen beskrivning',
    'projectDetails': 'Projektdetaljer',
    'category': 'Kategori',
    'dueDate': 'Slutdatum',
    'assignee': 'Tilldelad',
    'edit': 'Redigera',
    'createNewProject': 'Skapa nytt projekt',
    'fillProjectDetails': 'Fyll i projektinformation',
    'projectName': 'Projektnamn',
    'description': 'Beskrivning',
    'enterProjectName': 'Ange projektnamn',
    'enterDescription': 'Ange beskrivning',
    'selectCategory': 'Välj kategori'
  },
  en: {
    'routeGame': 'Route Choice Game',
    'courseSetter': 'Course Setter',
    'profile': 'Profile',
    'points': 'points',
    'routeChoose': 'Route Selector',
    'routeInstruction': 'Choose the correct direction for this route to earn points',
    'leaderboard': 'Leaderboard',
    'comingSoon': 'Coming Soon',
    'comingSoonDescription': 'New exciting features are on the way!',
    'orienteers': 'orienteers',
    'orienteeringEnthusiast': 'Orienteering Enthusiast',
    'rank': 'Rank',
    'yourStatistics': 'Your Statistics',
    'avgResponseTime': 'Average Response Time',
    'totalAttempts': 'Total Attempts',
    'accuracy': 'Accuracy',
    'correctChoices': 'Correct Choices',
    'incorrectChoices': 'Incorrect Choices',
    'you': 'you',
    'profileUpdated': 'Profile Updated',
    'profileUpdateSuccess': 'Your profile has been updated successfully',
    'invalidName': 'Invalid Name',
    'nameEmpty': 'Name cannot be empty',
    'excellent': 'Excellent!',
    'good': 'Good!',
    'correct': 'Correct!',
    'wrong': 'Wrong!',
    // Course Setter translations
    'newEvent': 'New Event',
    'myMaps': 'My Maps',
    'mapUploadedSuccessfully': 'Map uploaded successfully',
    'success': 'Success',
    'eventDate': 'Event Date',
    'previewMode': 'Preview Mode',
    'editMode': 'Edit Mode',
    'print': 'Print',
    'toggleLayers': 'Toggle Layers',
    'export': 'Export',
    'back': 'Back',
    'save': 'Save',
    'pointerTool': 'Pointer',
    'moveMap': 'Move Map',
    'addControl': 'Add Control',
    'addStart': 'Add Start',
    'addFinish': 'Add Finish',
    'zoomIn': 'Zoom In',
    'zoomOut': 'Zoom Out',
    'advancedTools': 'Advanced Tools',
    'crossingPoint': 'Crossing Point',
    'uncrossableBoundary': 'Uncrossable Boundary',
    'outOfBounds': 'Out of Bounds',
    'waterStation': 'Water Station',
    'resetView': 'Reset View',
    'printSettings': 'Print Settings',
    'configurePrintSettingsFor': 'Configure print settings for',
    'paperSize': 'Paper Size',
    'selectPaperSize': 'Select paper size',
    'orientation': 'Orientation',
    'portrait': 'Portrait',
    'landscape': 'Landscape',
    'mapScale': 'Map Scale',
    'copies': 'Copies',
    'include': 'Include',
    'controlDescriptions': 'Control Descriptions',
    'courseDetails': 'Course Details',
    'cancel': 'Cancel',
    'printArea': 'Print Area',
    'showCourses': 'Show Courses',
    'showControlNumbers': 'Show Control Numbers',
    'errorMapNotFound': 'Error: Map not found',
    'myPurplePenProjects': 'My Purple Pen Projects',
    'newProject': 'New Project',
    'previousProjects': 'Previous Projects',
    'viewManageProjects': 'View and manage projects',
    // Auth translations
    'signIn': 'Sign In',
    'signOut': 'Sign Out',
    'register': 'Register',
    'email': 'Email',
    'password': 'Password',
    'name': 'Name',
    'fullName': 'Full Name',
    'signingIn': 'Signing in...',
    'registering': 'Registering...',
    'signInError': 'Sign In Error',
    'signUpError': 'Registration Error',
    'signOutError': 'Sign Out Error',
    'verifyEmail': 'Verify Your Email',
    'verifyEmailDescription': 'We have sent a verification link to your email. Please click the link to activate your account.',
    'welcomeTo': 'Welcome to',
    'authDescription': 'Sign in to your account or create a new one to save your progress and compete on the leaderboard.',
    'authDisclaimer': 'By continuing, you agree to our Terms of Service and Privacy Policy.',
    'guest': 'Guest',
    'or': 'or',
    'projectManager': 'Project Manager',
    'noCategories': 'No categories',
    'allCategories': 'All categories',
    'selectedCategories': 'Selected categories',
    'training': 'Training',
    'club': 'Club',
    'national': 'National',
    'other': 'Other',
    'projectCreated': 'Project created',
    'hasBeenCreated': 'has been created',
    'projectShared': 'Project shared',
    'projectSharedWith': 'Project has been shared with',
    'permissionUpdated': 'Permission updated',
    'sharingPermissionUpdated': 'Sharing permission has been updated',
    'accessRemoved': 'Access removed',
    'userAccessRemoved': 'User access has been removed',
    'share': 'Share',
    'sharedWith': 'Shared with',
    'error': 'Error',
    'emailRequired': 'Email is required',
    'invalidEmail': 'Invalid email',
    'shareProject': 'Share project',
    'shareProjectDescription': 'Invite other users to collaborate on this project',
    'enterName': 'Enter name',
    'permission': 'Permission',
    'selectPermission': 'Select permission',
    'canView': 'Can view',
    'canSuggest': 'Can suggest',
    'canEdit': 'Can edit',
    'projectsList': 'Projects list',
    'calendar': 'Calendar',
    'noProjects': 'No projects',
    'createYourFirstProject': 'Create your first project',
    'createProject': 'Create project',
    'projectCalendar': 'Project calendar',
    'viewUpcomingDeadlines': 'View upcoming deadlines',
    'noDescription': 'No description',
    'projectDetails': 'Project details',
    'category': 'Category',
    'dueDate': 'Due date',
    'assignee': 'Assignee',
    'edit': 'Edit',
    'createNewProject': 'Create new project',
    'fillProjectDetails': 'Fill in project details',
    'projectName': 'Project name',
    'description': 'Description',
    'enterProjectName': 'Enter project name',
    'enterDescription': 'Enter description',
    'selectCategory': 'Select category'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // Try to get language preference from localStorage
    const savedLanguage = localStorage.getItem('orienteering-language');
    return (savedLanguage === 'en' || savedLanguage === 'sv') ? savedLanguage : 'sv';
  });

  // Save language preference to localStorage
  useEffect(() => {
    localStorage.setItem('orienteering-language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
