
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { enhanceSupabaseFetch } from '@/lib/networkUtils';

const SUPABASE_URL = "https://swscowqollkutgnamdye.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3c2Nvd3FvbGxrdXRnbmFtZHllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyODkzNjUsImV4cCI6MjA1OTg2NTM2NX0.b_IKgQJek8_0arKEwydWHBFf2B_TSOOWHqY-zTxMeqc";

// Enhance fetch for better network detection
enhanceSupabaseFetch();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  },
  global: {
    // Add custom headers for debugging
    headers: {
      'X-Client-Info': 'ol-app-frontend'
    }
  }
});
